### ISSUE TITLE
Can't Run

### ISSUE THREAD

**Issue by ypawar159** [DPRCZ/gpsp#9]
I have precompiled binaries of gpsp. When I run it from terminal it makes the screen go black and then i can't do anything. Only rebooting from ssh help in such situation. Though I have found a trick to make it work:
Log in using SSH
run ./gpsp
CTRL^Z
fg
Now it shows the game on the pi but can't give input to it.
Help needed to run locally successfully.

**Comment by DPRCZ** [comment]
Try to start it without x-windows  and/or check the size of GPU ram in 
raspi-config.
D.

Dne 21.5.2015 v 18:43 ypawar159 napsal(a):

**Comment by ypawar159** [comment]
I have set gpu ram to 256MB
and i am using minibian which doesn't have X installed only terminal to boot to.
I am using neosec tinylcd 3.5". Using fbcp to mirror default display output to lcd.
I have successfully played video using omxplayer without any problem.

**Comment by DPRCZ** [comment]
I've test gpsp only with raspberian. I'm sorry but I don't know what is 
different between minibian and raspberian.

Dne 21.5.2015 v 21:16 ypawar159 napsal(a):

**Comment by ypawar159** [comment]
Its just raspbian without X, only bare linux boots into terminal.

**Comment by ypawar159** [comment]
Hey good news!
Since the precompiled binaries were not working I tried to compile it on raspberry pi itself. Then got error that bcm_host.h not found. Hunting on the google I found that libraspberrypi-dev package needs to be installed for applications using opengl. So after installing it and setting gpu memory to 128MB I have it running. 
Thank you.
